#!/bin/bash -e

# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

TESTRUN_DIR=/usr/local/testrun
cd $TESTRUN_DIR

python3 -m venv venv

source venv/bin/activate

echo Installing python dependencies
pip3 install -r framework/requirements.txt >> /dev/null

deactivate

# Copy the default configuration
echo Copying default configuration
cp -u local/system.json.example local/system.json

# Set owner of local dir to sudo user
echo Correcting file ownership
chown -R $SUDO_USER /usr/local/testrun/local

echo Successfully installed Testrun
