version: "3.7"

services:

  base:
    build:
      context: network/modules/base
      dockerfile: base.Dockerfile
    image: test-run/base
    container_name: tr-ct-base

  ovs:
    depends_on:
      - base
    build:
      context: network/modules/ovs
      dockerfile: ovs.Dockerfile
    image: test-run/ovs
    network_mode: host
    container_name: tr-ct-ovs
    stdin_open: true
    privileged: true
    volumes:
      - $PWD/network/modules/ovs/python:/ovs/python
      # Mount host open vswitch socket to allow container
      # access to control open vswitch on the host
      - /var/run/openvswitch/db.sock:/var/run/openvswitch/db.sock
      # Mount host network namespace to allow container
      # access to assign proper namespaces to containers
      - /var/run/netns:/var/run/netns

  netorch:
    depends_on:
      - base
    build:
      context: .
      dockerfile: orchestrator.Dockerfile
    image: test-run/orchestrator
    network_mode: host
    privileged: true
    volumes:
      - $PWD/cmd:/orchestrator/cmd
      - $PWD/network:/orchestrator/network
      - $PWD/python:/orchestrator/python
      # Mount host docker socket to allow container access
      # control docker containers on the host
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount host open vswitch socket to allow container
      # access to control open vswitch on the host
      - /var/run/openvswitch/db.sock:/var/run/openvswitch/db.sock
      # Mount host network namespace to allow container
      # access to assign proper namespaces to containers
      - /var/run/netns:/var/run/netns
      # Mount the host process information to allow container
      # access to configure docker containers and namespaces properly
      - /proc:/proc
    container_name: network_orchestrator
    stdin_open: true
    working_dir: /orchestrator
    #entrypoint: ["cmd/start"]
    # Give more time for stopping so when we stop the container it has 
    # time to stop all network services gracefuly
    stop_grace_period: 60s
    entrypoint: ["python3","-u","python/src/run.py"]
