#!/bin/bash

# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ERROR_LIMIT=25

sudo cmd/install

source venv/bin/activate
sudo pip3 install pylint==3.0.3

files=$(find . -path ./venv -prune -o -name '*.py' -print)

OUT=pylint.out

rm -f $OUT && touch $OUT

pylint $files -ry --extension-pkg-allow-list=docker --evaluation="error + warning + refactor + convention" 2>/dev/null | tee -a $OUT

new_errors=$(cat $OUT | grep -oP  "(?!=^Your code has been rated at)([0-9]+)(?=\.00/10[ \(]?)" )

echo "$new_errors > $ERROR_LIMIT?"
if (( $new_errors > $ERROR_LIMIT)); then
    echo new errors $new_errors > error limit $ERROR_LIMIT 
    echo failing ..
    exit 1
fi

exit 0