#!/bin/bash

# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Install python venv
python3 -m venv venv

# Activate the venv
source venv/bin/activate

# Install pylint
pip install pylint==3.2.6

# Declare the applicable files
files=$(find . -path ./venv -prune -o -name '*.py' -print)

# Define the pylint output file
OUT=pylint.out

# Remove it if it already exists
rm -f $OUT

# Run pylint against the target files
# Change the evaluation to total the number of errors
# Output to the specified output file
pylint $files -ry --extension-pkg-allow-list=docker --evaluation="error + warning + refactor + convention" 2>/dev/null | tee -a $OUT

# Obtain the total number of errors from the pylint out file
errors=$(cat $OUT | grep -oP  "(?!=^Your code has been rated at)([0-9]+)(?=\.00/10[ \(]?)" )

# Check if any errors exist
if (( $errors > 0 )); then
    echo "$errors pylint issues have been identified. These must be resolved before merging."
    exit 1
fi

exit 0