Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "ubuntu-vm"
  config.vm.network "private_network",
    libvirt__network_name: "hostonly-noip",
    auto_config: false,
    mac: "52:54:00:12:34:56"
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 2048
    libvirt.cpus = 2
    libvirt.graphics_type = "none"
  end
  if ENV['DEVICE'] == 'COMPLIANT'
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision-compliant.yml"
    end
  end
end
