Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/ubuntu-24.04"
  config.vm.box_version = "20251126.0.0"
  config.vm.hostname = "ubuntu-vm"
  if ENV['DEVICE'] == 'COMPLIANT'
    config.vm.network "private_network",
    libvirt__network_name: "hostonly-noip",
    auto_config: false,
    mac: "f0:d4:e2:f2:f5:41"
  end
  if ENV['DEVICE'] == 'NON-COMPLIANT'
    config.vm.network "private_network",
    libvirt__network_name: "hostonly-noip",
    auto_config: false,
    mac: "54:53:52:51:50:49"
  end
  
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 2048
    libvirt.cpus = 2
    libvirt.graphics_type = "none"
  end
  if ENV['DEVICE'] == 'COMPLIANT'
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision-compliant.yml"
    end
  end
  if ENV['DEVICE'] == 'NON-COMPLIANT'
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision-non-compliant.yml"
    end
  end
end
