#!/bin/bash -e

# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Build the UI
echo Building the user interface

# Build UI builder image
if docker build -t testrun/build-ui -f modules/ui/build.Dockerfile . ; then
  echo Successully built the ui builder
else
  echo An error occured whilst building the ui builder
  exit 1
fi

# Check that the container is not already running
docker kill tr-ui-build 2> /dev/null || true

# Start the docker container so we can access the files
docker run --rm -d --name tr-ui-build testrun/build-ui

# Copy the UI (built) from the container
docker cp tr-ui-build:/modules/ui/dist modules/ui/dist

# Kill the container
docker kill tr-ui-build
