#!/bin/bash -e

# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo Installing application dependencies

if [[ -z "${TESTRUN_DIR}" ]]; then
  TESTRUN_DIR=/usr/local/testrun
else
  TESTRUN_DIR="${TESTRUN_DIR}"
fi

echo Installing Testrun at $TESTRUN_DIR
cd $TESTRUN_DIR

python3 -m venv venv

source venv/bin/activate

pip3 install -r framework/requirements.txt

# Copy the default configuration
cp -n local/system.json.example local/system.json

# Set file permissions on system config
# This does not work on GitHub actions
if logname ; then
  USER_NAME=$(logname)
  sudo chown "$USER_NAME" local/system.json
fi

deactivate

# Build docker images
sudo cmd/build

echo Finished installing Testrun
