#!/bin/bash -e

# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [[ "$EUID" -ne 0 ]]; then
    echo "Must run as root. Use sudo cmd/start"
    exit 1
fi

# Ensure that /var/run/netns folder exists
mkdir -p /var/run/netns

# Clear up existing runtime files
rm -rf runtime

# Check if python modules exist. Install if not
[ ! -d "venv" ] && cmd/install

# Activate Python virtual environment
source venv/bin/activate

python -u framework/test_runner.py $@

# TODO: Work in progress code for containerization of OVS module
# asyncRun() {
#     "$@" &
#     pid="$!"
#     echo "PID Running: " $pid
#     trap "echo 'Stopping PID $pid'; kill -SIGTERM $pid" SIGINT SIGTERM

#     sleep 10

#     # A signal emitted while waiting will make the wait command return code > 128
#     # Let's wrap it in a loop that doesn't end before the process is indeed stopped
#     while kill -0 $pid > /dev/null 2>&1; do
#     #while $(kill -0 $pid 2>/dev/null); do
#         wait
#     done
# }

# # -u flag allows python print statements
# # to be logged by docker by running unbuffered
# asyncRun python3 -u python/src/run.py $@

deactivate