#!/bin/bash -e

# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

TESTRUN_OUT=testrun.log

ifconfig

# Setup requirements
sudo apt-get update
sudo apt-get install openvswitch-common openvswitch-switch tcpdump jq moreutils coreutils isc-dhcp-client

# Setup device network
sudo ip link add dev endev0a type veth peer name endev0b
sudo ip link set dev endev0a up
sudo ip link set dev endev0b up
sudo docker network create -d macvlan -o parent=endev0b endev0

# Start OVS
sudo /usr/share/openvswitch/scripts/ovs-ctl start

# Build Test Container
sudo docker build ./testing/docker/ci_baseline -t ci1 -f  ./testing/docker/ci_baseline/Dockerfile

# Copy configuration to testrun
sudo cp testing/baseline/system.json local/system.json

# Copy device configs to testrun
sudo cp -r testing/device_configs/* local/devices

sudo bin/testrun --single-intf --no-ui --validate > $TESTRUN_OUT 2>&1 & 
TPID=$!

# Time to wait for testrun to be ready
WAITING=750
for i in `seq 1 $WAITING`; do
    if [[ -n $(fgrep "Waiting for devices on the network" $TESTRUN_OUT) ]]; then
        break
    fi

    if [[ ! -d /proc/$TPID ]]; then
        cat $TESTRUN_OUT
        echo "Error encountered starting test run"
        exit 1
    fi
   
    sleep 1
done

if [[ $i -eq $WAITING ]]; then
    cat $TESTRUN_OUT
    echo "Failed after waiting $WAITING seconds for testrun to start"
    exit 1
fi

# Start test container
sudo docker run --network=endev0 --cap-add=NET_ADMIN -v /tmp:/out --privileged ci1

echo "Done baseline test"

more $TESTRUN_OUT

# Needs to be sudo because this invokes bin/testrun 
sudo venv/bin/python3 -m pytest -v testing/baseline/test_baseline.py

# Clean the device network
sudo ip link del dev endev0a
sudo docker network rm endev0

exit $?