#!/bin/bash

# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o xtrace
ip a
TEST_DIR=/tmp/results
MATRIX=testing/tests/test_tests.json

mkdir -p $TEST_DIR

# Setup requirements
sudo apt-get update
sudo apt-get install openvswitch-common openvswitch-switch tcpdump jq moreutils coreutils isc-dhcp-client

pip3 install pytest

# Start OVS
# Setup device network
sudo ip link add dev endev0a type veth peer name endev0b
sudo ip link set dev endev0a up
sudo ip link set dev endev0b up
sudo docker network create -d macvlan -o parent=endev0b endev1

sudo /usr/share/openvswitch/scripts/ovs-ctl start

# Build Test Container
sudo docker build ./testing/docker/ci_test_device1 -t ci_test_device1 -f  ./testing/docker/ci_test_device1/Dockerfile

cat <<EOF >local/system.json
{
  "network": {
    "device_intf": "endev0a",
    "internet_intf": "eth0"
  },
  "log_level": "DEBUG",
  "monitor_period": 30
}
EOF

mkdir -p local/devices
cp -r testing/device_configs/* local/devices

sudo cmd/install

TESTERS=$(jq -r 'keys[]' $MATRIX)
for tester in $TESTERS; do
  testrun_log=$TEST_DIR/${tester}_testrun.log
  device_log=$TEST_DIR/${tester}_device.log

  image=$(jq -r .$tester.image $MATRIX)
  ethmac=$(jq -r .$tester.ethmac $MATRIX)
  args=$(jq -r .$tester.args $MATRIX)

  touch $testrun_log
  sudo timeout 900 bin/testrun --single-intf --no-ui > $testrun_log 2>&1 &
  TPID=$!

  # Time to wait for testrun to be ready
  WAITING=600
  for i in `seq 1 $WAITING`; do
    tail -1 $testrun_log
      if [[ -n $(fgrep "Waiting for devices on the network" $testrun_log) ]]; then
          break
      fi

      if [[ ! -d /proc/$TPID ]]; then
          cat $testrun_log
          echo "error encountered starting test run"
          exit 1
      fi
    
      sleep 1
  done

  if [[ $i -eq $WAITING ]]; then
      cat $testrun_log
      echo "failed after waiting $WAITING seconds for test-run start"
      exit 1
  fi

  # Load Test Container
  sudo docker run -d \
    --network=endev1 \
    --mac-address=$ethmac \
    --cap-add=NET_ADMIN \
    -v /tmp:/out \
    --privileged \
    --name=$tester \
    ci_test_device1 $args
  
  wait $TPID
  # Following line indicates that tests are completed but wait till it exits
  # Completed running test modules on device with mac addr 7e:41:12:d2:35:6a
  #Change this line! - LOGGER.info(f"""Completed running test modules on device
  #          with mac addr {device.mac_addr}""")

  ls runtime
  more runtime/network/*.log
  sudo docker kill $tester
  sudo docker logs $tester | cat 
  
  cp runtime/test/${ethmac//:/}/report.json $TEST_DIR/$tester.json
  more $TEST_DIR/$tester.json
  more $testrun_log

done

pytest -v testing/tests/test_tests.py

exit $?
