# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

name: Security

permissions:
  contents: read
  pull-requests: write

on:
  # For Branch-Protection check. Only the default branch is supported. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
  branch_protection_rule:
  push:
    branches: [ "main" ]
  pull_request:
  schedule:
    - cron: '0 13 * * *'

jobs:
  secret_scanning:
    name: Trufflehog Secrets Scan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@00155c9dc586f34d189adc83d3ac2698c2ec551f # v3.95.8
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha || github.event.before }}
          head: ${{ github.event.pull_request.head.sha || github.sha }}
          extra_args: --only-verified
  validate_syntax:
    name: Validate JSON & YAML Syntax
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Run JSON/YAML Syntax validator
        uses: GrantBirki/json-yaml-validate@3ff75979f3b21171f2e8a44705f0ff4bed30bbc0 # v5.0.0
        with:
          mode: "fail"
          comment: "true"
          update_comment: "true"
          base_dir: "."
          json_exclude_regex: '.*(tsconfig.*\.json|\.venv|node_modules)'
          yaml_exclude_regex: '.*(\.venv|node_modules)'
  dockerfile_scan:
    name: Dockerfile Scan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Run Hadolint
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 #v3.3.0
        with:
          dockerfile: "*Dockerfile"
          recursive: true
          ignore: DL3007,DL3008,DL3015,DL3059
          failure-threshold: warning
  trivy_sca_scan:
    name: Trivy SCA Security Scan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Run Trivy in Filesystem mode
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 #0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
 

  


